- practice-app/website/__init__.py
- practice-app/website/api/event.py
- practice-app/website/models.py
- practice-app/website/templates/base.html
- practice-app/website/templates/create_event.html
- practice-app/website/templates/view_event.html
- practice-app/website/views.py
I have partially completed the features related to events:
- Creating an event
- Viewing an event
My work is summarized in #158. I have done the following:
- [__init__.py](https://github.com/bounswe/bounswe2022group7/blob/practice-app/feature/events/practice-app/website/__init__.py): Add `event` blueprint to the app
- [event.py](https://github.com/bounswe/bounswe2022group7/compare/practice_app...practice-app/feature/events#diff-4f58be1e33d7c73423d23c6a0c72b520b40b83adbb9f8bf4c13dd7f3534f415a): Define `event` blueprint
- [models.py](https://github.com/bounswe/bounswe2022group7/compare/practice_app...practice-app/feature/events#diff-0865db035925e3c7ddd3a74930a04a9955642930ea4a026906e447eac2e960a1): Change fields of the Event entity
- …
> Merge "events" feature branch into practice-app branch

- practice-app/requirements.txt
- practice-app/website/__init__.py
- practice-app/website/auth.py
- practice-app/website/models.py
- I changed session based authentication to token based authentication.
- We don't use flask-login anymore. Instead we are using the flask-jwt-extended library.
The server returns an access token.
You can authorize to a jwt-protected api.
In order to protect your api endpoint with an access token, all you need to do is:
```python
from flask_jwt_extended import jwt_required
@auth.route("/protected", methods=["GET"])  # change this route to your specific route and methods
@jwt_required()
def protected():
return jsonify(logged_in_as=current_user.email), 200
```
As seen here, you can access the logged in user object simply using the ``current_user`` variable after doing
```python
from flask_jwt_extended import current_user
```
> Token based authentication

- practice-app/website/__init__.py
- practice-app/website/api/event.py
- practice-app/website/api/home.py
- practice-app/website/models.py
- practice-app/website/templates/base.html
- practice-app/website/templates/create_event.html
- practice-app/website/templates/home.html
- practice-app/website/templates/view_event.html
- practice-app/website/test/test_event.py
In the [event feature branch](https://github.com/bounswe/bounswe2022group7/tree/practice-app/feature/events), I have done the following:
- I merged the changes I had made in the [home & search feature branch](https://github.com/bounswe/bounswe2022group7/tree/practice-app/feature/home%26search).
- I created a [test folder](https://github.com/bounswe/bounswe2022group7/tree/practice-app/feature/events/practice-app/website/test) and prepared a [test_event.py](https://github.com/bounswe/bounswe2022group7/blob/practice-app/feature/events/practice-app/website/test/test_event.py) file where I used `unittest` to test my code in [event.py](https://github.com/bounswe/bounswe2022group7/blob/practice-app/feature/events/practice-app/website/api/event.py).
My work can be tracked in #158 and #166. I will …
> Merge event feature branch into the practice_app

- practice-app/website/__init__.py
- practice-app/website/api/auth.py
- practice-app/website/auth.py
- practice-app/website/models.py
- practice-app/website/templates/base.html
- practice-app/website/templates/login.html
- practice-app/website/templates/signup.html
- practice-app/website/views.py
I added functionality for signing up as an artist by simpy adding an "is_artist" field to the api. Since logging in is done in the same manner for all kind of users, I haven't changed anything for the login endpoint.
> Sign up & login functionality

- practice-app/.gitignore
- practice-app/Dockerfile
- practice-app/docker-compose.yml
Files for deploying the app were added in the practice-app/deployment branch. Progress can be tracked in #170. Once the files were added, they were tested in #171 by deploying the app on EC2.
These issues were reviewed and approved. Therefore I am merging the practice-app/deployment branch into practice_app branch.
> Add Docker files

- practice-app/website/api/home.py
- practice-app/website/api/jwt.py
- practice-app/website/test/test_event.py
- practice-app/website/test/test_home.py
After the changes in the token system, I needed to update the unittests in the [test_event.py](https://github.com/bounswe/bounswe2022group7/blob/practice_app/practice-app/website/test/test_event.py) file. Also, I added tests for the home endpoint.
There is a minor merge conflict in the [jwt.py](https://github.com/bounswe/bounswe2022group7/blob/practice_app/practice-app/website/api/jwt.py) file. I will try to resolve it.
> Update home and event unittests

- practice-app/requirements.txt
- practice-app/website/__init__.py
- practice-app/website/api/art_item.py
- practice-app/website/api/doc/art_item_GET.yml
- practice-app/website/api/doc/art_item_POST.yml
- practice-app/website/settings.py
- practice-app/website/templates/base.html
- practice-app/website/templates/create_art_item.html
- practice-app/website/templates/view_art_item.html
- practice-app/website/views.py
* Tracking of this pull request can be seen in #173. 
* The feature is fully implemented except the unit test files. 
* Unit tests shall be merged after completion. 
* Documentation is also available in the `practice-app/feature/art-items` branch.
> Merge practice-app/feature/art-items to practice_app

- practice-app/website/__init__.py
- practice-app/website/api/profile.py
- practice-app/website/templates/base.html
- practice-app/website/templates/view_profile.html
- practice-app/website/test/test_profile.py
- practice-app/website/views.py
I have added the functionality to view user profile.
Below is the result of Postman endpoint test:
closes #172
> View Profile

- practice-app/website/__init__.py
- practice-app/website/api/art_galleries.py
- practice-app/website/templates/art_galleries.html
- practice-app/website/test/test_galleries.py
- practice-app/website/views.py
Implemented /api/art_galleries endpoint which lists 5 art galleries available for creating events. It uses an external random address api. All the tests pass in my local.
> Create /api/art_galleries endpoint

- practice-app/website/templates/home.html
- practice-app/website/test/test_art_item.py
* As I had already merged my feature branch into the main `practice_app` branch before (check #193), these two branches have many similarities.
* The main difference is that I have now completed writing the code for unit testing, too (#183).
* The feature branch is now fully implemented involving the documentations. You can track the progress of implementation of Art Item related features in #173.
> Art Item unit tests are also completed, merge to practice_app

- practice-app/website/api/doc/profile_GET.yml
- practice-app/website/api/profile.py
I have added a yml file that documents behavior of profile API endpoint.
> Added documentation for profile API endpoint

- practice-app/website/templates/base.html
View profile link was shown below login button. That link is already in navbar so I removed the link from top bar.
> Remove view profile from top bar

- practice-app/website/api/doc/request_verification_POST.yml
- practice-app/website/api/doc/review_verification_request_POST.yml
- practice-app/website/api/verification.py
I have updated some error codes and their corresponding documentation.
> Practice app/feature/verification1.2

- practice-app/website/api/discussion_forum.py
- practice-app/website/test/test_discussion_comments.py
I have modified the sample data in unittests:
- removed unnecessary samples
- made sure comments were short in order to not exceed the translation limit in translate external API used
Should be merged into the practice_app branch
> Merge practice-app/feature/discussion-comments into practice_app

- frontend/src/App.js
- frontend/src/pages/Authentication/SignInPage.js
- frontend/src/pages/Authentication/SignUpPage.js
With this PR, I am adding the sign-up and sign-in pages added with #284. Details about the implementation, next steps and are available in #284.
> Add sign-up and sign-in pages (FE, #284)

- android/lib/main.dart
- android/lib/models/user_model.dart
- android/lib/pages/home_page.dart
- android/lib/pages/login.dart
- android/lib/pages/profile_page.dart
- android/lib/pages/register.dart
- android/lib/providers/user_provider.dart
- android/lib/shared_prefs/user_preferences.dart
- android/pubspec.lock
- android/pubspec.yaml
As mentioned in #292, the implementation of the user provider is now completed and ready for review.
- User provider and shared preferences classes are implemented.
- The information entered in login and register pages are stored in shared preferences.
- I have added a CurrentUser class with a bearer token attribute that extends the User class.
- To demonstrate how user provider works, I used it in homepage. Now, if user is logged in the button on the top left redirects to profile page or else it redirects to login page.
- I have also done the logout functionality.
- Finally, the username that is stored is shown in the profile page by giving it in the arguments from user provider to profile page.
> Implemented user provider

- backend/src/main/kotlin/com/group7/artshare/entity/AccountInfo.kt
- backend/src/main/kotlin/com/group7/artshare/entity/RegisteredUser.kt
Code for [issue #305](https://github.com/bounswe/bounswe2022group7/issues/305). AccountInfo class is implemented and associated with RegisteredUser
> implement account info class

- backend/src/main/kotlin/com/group7/artshare/controller/Homepage.kt
related implementation with [issue #306] (https://github.com/bounswe/bounswe2022group7/issues/306)
> hard coded data is removed

- android/lib/main.dart
- android/lib/pages/login.dart
- android/lib/pages/register.dart
- android/lib/util/validators.dart
- android/lib/widgets/form_widgets.dart
- android/lib/widgets/logo.dart
- android/pubspec.lock
- android/pubspec.yaml
As mentioned in #294, I have updated the register page so that it looks similar to login page and added extra name, surname, age, location and user type inputs written in the requirements. I have also added screenshots of new register page in the issue. Here are the changes made in this pull request:
- UI of the register page is changed.
- Name, surname, age, location and user type inputs are added to register page.
- Username field in the login page is changed as email field.
- Password validator is changed according to the requirements.
> Update register page

- backend/src/main/kotlin/com/group7/artshare/controller/ArtItemController.kt
- backend/src/main/kotlin/com/group7/artshare/controller/DataProp.kt
- backend/src/main/kotlin/com/group7/artshare/entity/ArtItem.kt
- backend/src/main/kotlin/com/group7/artshare/entity/ArtItemInfo.kt
implementation of [issue] (https://github.com/bounswe/bounswe2022group7/issues/302)
> Single art_item endpoint

- android/lib/config/api_endpoints.dart
- android/lib/data/data.dart
- android/lib/main.dart
- android/lib/models/user_model.dart
- android/lib/network/register/register_input.dart
- android/lib/network/register/register_output.dart
- android/lib/network/register/register_service.dart
- android/lib/pages/home_page.dart
- android/lib/pages/login.dart
- android/lib/pages/register.dart
- android/lib/providers/register_provider.dart
- android/lib/util/validators.dart
- android/lib/widgets/alert.dart
- android/lib/widgets/loading.dart
- android/pubspec.lock
- android/pubspec.yaml
As mentioned in #318, the implementation of register functionality by connecting the form to back end is now complete.
- Created a file for storing back end endpoint URL's. For now the server IP points at localhost address reachable from emulator.
- A validator is added for user type field to make user type selection mandatory.
- User type field is added to user model.
- I have created register input and register output objects to convert json objects to flutter objects.
- I have also created a provider class to show a loading widget when waiting for network call.
- Finally I have created a function that sends a register input class and takes a register output class from the back end by using flutter http library.
This pull request closes #318.
> Connected register form to backend

- android/lib/config/api_endpoints.dart
- android/lib/main.dart
- android/lib/models/user_model.dart
- android/lib/network/login/login_input.dart
- android/lib/network/login/login_output.dart
- android/lib/network/login/login_service.dart
- android/lib/network/register/register_output.dart
- android/lib/network/register/register_service.dart
- android/lib/pages/home_page.dart
- android/lib/pages/login.dart
- android/lib/pages/profile_page.dart
- android/lib/pages/register.dart
- android/lib/providers/login_provider.dart
- android/pubspec.lock
As mentioned in https://github.com/bounswe/bounswe2022group7/issues/335 I have changed the successful signup check from status code to response body. Now the application redirects to login page if response body is "true".
I have also changed the endpoint URL from "/register" to "/signup" as implemented in backend.
I have tested the functionality in my computer. You can find a screenshot after a successful signup below.
> Updated the Register Network Function According to Backend Implementation

- backend/src/main/kotlin/com/group7/artshare/configuration/SecurityConfiguration.kt
Code for [issue #341](https://github.com/bounswe/bounswe2022group7/issues/341)
> allow everyone to send requests for generic endpoints

- backend/src/main/kotlin/com/group7/artshare/entity/AccountInfo.kt
- backend/src/main/kotlin/com/group7/artshare/entity/RegisteredUser.kt
implementation of [issue](https://github.com/bounswe/bounswe2022group7/issues/323)
and also this resolves the [issue](https://github.com/bounswe/bounswe2022group7/issues/344)
Related art item endpoints are tested, screenshots of the outputs are attached below:
> Json Related Bug Fix

- backend/src/main/kotlin/com/group7/artshare/entity/AccountInfo.kt
- backend/src/main/kotlin/com/group7/artshare/entity/RegisteredUser.kt
- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/Authentication/SignInPage.js
- frontend/src/pages/Authentication/SignUpPage.js
- frontend/src/pages/HomePage/HomePage.js
I have updated the functionality of sign up and login pages by adding form validation, backend connection and necessary feedback mechanisms (error alert, information alert, loading icon). All changes are documented in issue #338. Two new packages are added for form validation: **yup**, **formik**.
With merging this branch sign-up and login functionalities of frontend will be completed.
Merging this pull request closes #338.
> [Frontend] Merge revised signup and signing pages to develop

- frontend/package.json
- frontend/src/App.js
- frontend/src/pages/ArtItemPage/ArtItemPage.js
- frontend/src/pages/EventPage/EventPage.js
With this PR, I am adding the event page:
Additionaly, there is an update to the docker-compose file fixing the proxy error in the development environment.
> Add event page

- backend/src/main/kotlin/com/group7/artshare/entity/AccountInfo.kt
- backend/src/main/kotlin/com/group7/artshare/request/SignupRequest.kt
- backend/src/main/kotlin/com/group7/artshare/service/SignupService.kt
Implementation of the [issue](https://github.com/bounswe/bounswe2022group7/issues/377).
Checked the database for the corresponding date_of_birth field.
> Age - dateOfBirth changement

- backend/src/main/kotlin/com/group7/artshare/controller/DataProp.kt
- backend/src/main/kotlin/com/group7/artshare/entity/ArtItem.kt
- backend/src/main/kotlin/com/group7/artshare/entity/Auction.kt
- backend/src/main/kotlin/com/group7/artshare/entity/AuctionInfo.kt
- backend/src/main/kotlin/com/group7/artshare/entity/Bid.kt
- backend/src/main/kotlin/com/group7/artshare/entity/Comment.kt
- backend/src/main/kotlin/com/group7/artshare/entity/Event.kt
- backend/src/main/kotlin/com/group7/artshare/entity/Notification.kt
- backend/src/main/kotlin/com/group7/artshare/entity/OnlineGallery.kt
- backend/src/main/kotlin/com/group7/artshare/entity/PhysicalExhibition.kt
- backend/src/main/kotlin/com/group7/artshare/entity/Recommendation.kt
- backend/src/main/kotlin/com/group7/artshare/entity/RegisteredUser.kt
- backend/src/main/resources/application.properties
implementation of the first part of the issue: https://github.com/bounswe/bounswe2022group7/issues/382
It runs without error and I checked the database to make sure about whether associations are implemented correctly or not.
> First Part of the Class Implementation

- backend/src/main/kotlin/com/group7/artshare/controller/DataProp.kt
- backend/src/main/kotlin/com/group7/artshare/entity/Comment.kt
- backend/src/main/kotlin/com/group7/artshare/entity/DiscussionPost.kt
- backend/src/main/kotlin/com/group7/artshare/entity/Report.kt
implementation of the second part of the issue: https://github.com/bounswe/bounswe2022group7/issues/382
It runs without error and I checked the database to make sure about whether associations are implemented correctly or not.
MutableList is used instead of List as previous [PR](https://github.com/bounswe/bounswe2022group7/pull/383) discussion.
> Second Part of the Class Implementation

- backend/pom.xml
- backend/src/main/kotlin/com/group7/artshare/controller/ArtItemController.kt
- backend/src/main/kotlin/com/group7/artshare/controller/DataProp.kt
- backend/src/main/kotlin/com/group7/artshare/entity/AccountInfo.kt
- backend/src/main/kotlin/com/group7/artshare/entity/ArtItem.kt
- backend/src/main/kotlin/com/group7/artshare/entity/Artist.kt
- backend/src/main/kotlin/com/group7/artshare/entity/Event.kt
- backend/src/main/kotlin/com/group7/artshare/entity/OnlineGallery.kt
- backend/src/main/kotlin/com/group7/artshare/entity/PhysicalExhibition.kt
- backend/src/main/kotlin/com/group7/artshare/entity/RegisteredUser.kt
Artist Class is implemented with the RegisteredUser inheritance.
There are two tables in the database that corresponds to them as we want:
RegisteredUser columns:
Artist columns:
Event inheritance is also changed due to some associations. Now there is also Event table in the database with the high level associations like participants.
Unnecessary use of List is also changed to Set.
Artist class is also tested with art_item endpoint, creator corresponds to Artist class:
```json
{
"id": 7,
"artItemInfo": {
"id": 8,
"name": "Starry Night",
"description": "A reflection of my soul from a fuzzy night.",
"category": "Classical",
"imageUrl": "https://media.overstockart.com/optimized/cache/data/product_images/VG485-1000x1000.jpg",
"labels": "[\"classical\", \"painting\"]"
},
"creator": { …
```
> Artist Class Implementation

- backend/src/main/kotlin/com/group7/artshare/request/SignupRequest.kt
- backend/src/main/kotlin/com/group7/artshare/service/SignupService.kt
PR for the issue https://github.com/bounswe/bounswe2022group7/issues/391
> remove optional signup request fields

- android/lib/data/data.dart
- android/lib/models/user_model.dart
- android/lib/network/register/register_input.dart
- android/lib/pages/login.dart
- android/lib/pages/profile_page.dart
- android/lib/pages/register.dart
- android/lib/widgets/form_widgets.dart
- android/pubspec.lock
- android/pubspec.yaml
You can view [the issue](https://github.com/bounswe/bounswe2022group7/issues/410) explaining the task that should be done with these changes.
-  Register page should not ask name, surname, age and country [anymore](https://github.com/bounswe/bounswe2022group7/commit/2fccca745f9319ec39b9cc3d1cb2903a2978b343#diff-a6181b73ebf4793998ecb26b6ced5685ee54145e95e388097a6bdbebd9db4e85).
- It seemed reasonable to [add a field for email to CurrentUser](https://github.com/bounswe/bounswe2022group7/commit/2fccca745f9319ec39b9cc3d1cb2903a2978b343#diff-e64ee8d0beb4ab78e93ac7dbc5f0064ca99a458feeabc655993ca017608e43ef) class so that we can compare a user with our current user in any place.
- Register page should not ask name, surname, age and country anymore; therefore, [it should not send any data to …
> Removal of Optional Fields from Register Page

- backend/src/main/kotlin/com/group7/artshare/controller/RegisteredUserController.kt
- backend/src/main/kotlin/com/group7/artshare/service/SignupService.kt
PR for the issue: https://github.com/bounswe/bounswe2022group7/issues/419
This is the result of successful signup:
> return token after signup

- .github/workflows/Android-CI.yml
- .github/workflows/Backend-CI.yml
- .github/workflows/Frontend-CI.yml
- android/test/widget_test/register_test.dart
This PR applies the changes and fixes described in #425. If the changes are succesful this PR should be automatically checked by Backend, Frontend and Android CI's.
> Update and fix continuous integration workflows 

- backend/src/main/kotlin/com/group7/artshare/configuration/SecurityConfiguration.kt
- backend/src/main/kotlin/com/group7/artshare/controller/ProfileController.kt
- backend/src/main/kotlin/com/group7/artshare/service/ProfileService.kt
PR for the issue: https://github.com/bounswe/bounswe2022group7/issues/416
These are the results of endpoint requests:
Without providing username (get user by token):
With providing username:
> implement get user endpoints for profile page

- backend/src/main/kotlin/com/group7/artshare/service/SignupService.kt
PR for the issue: https://github.com/bounswe/bounswe2022group7/issues/423
> add signup functionality for Artist users

- backend/src/main/kotlin/com/group7/artshare/entity/ArtItem.kt
- backend/src/main/kotlin/com/group7/artshare/entity/Artist.kt
- backend/src/main/kotlin/com/group7/artshare/entity/Auction.kt
- backend/src/main/kotlin/com/group7/artshare/entity/AuctionInfo.kt
- backend/src/main/kotlin/com/group7/artshare/entity/Bid.kt
- backend/src/main/kotlin/com/group7/artshare/entity/Comment.kt
- backend/src/main/kotlin/com/group7/artshare/entity/DiscussionPost.kt
- backend/src/main/kotlin/com/group7/artshare/entity/Event.kt
- backend/src/main/kotlin/com/group7/artshare/entity/Notification.kt
- backend/src/main/kotlin/com/group7/artshare/entity/OnlineGallery.kt
- backend/src/main/kotlin/com/group7/artshare/entity/PhysicalExhibition.kt
- backend/src/main/kotlin/com/group7/artshare/entity/Recommendation.kt
- backend/src/main/kotlin/com/group7/artshare/entity/RegisteredUser.kt
- backend/src/main/kotlin/com/group7/artshare/entity/Report.kt
PR for the issue :https://github.com/bounswe/bounswe2022group7/issues/384
Changes made according to: https://www.baeldung.com/jackson-bidirectional-relationships-and-infinite-recursion#bd-managed-back-reference
> add JsonIdentityInfo for bidirectional relations

- frontend/src/App.js
- frontend/src/common/CommentSection.js
- frontend/src/common/NewComment.js
- frontend/src/common/UserCard.js
- frontend/src/components/IconWithText.js
- frontend/src/components/ImageComponent.js
- frontend/src/components/ImageDisplay.js
- frontend/src/components/MapComponent.js
- frontend/src/pages/ArtItemPage/ArtItemPage.js
- frontend/src/pages/DiscussionPage/DiscussionPostPage.js
- frontend/src/pages/EventPage/CreatePhysicalEventPage.js
- frontend/src/pages/EventPage/EventPage.js
I have updated the styling of some pages as I listed in #490. You can find the new page styles in the issue.
> Frontend content page styling

- .github/workflows/Annotation-AWS-Deployment.yml
- .github/workflows/Annotation-CI.yml
- annotations/app.js
- deployment/annotation-task-definition.json
- deployment/backend-task-definition.json
- deployment/frontend-task-definition.json
- frontend/nginx.conf
As described in #517, the annotation microservice needed deployment and testing configuration. This PR implements the necessary configuration and changes for the automatic deployment of annotation microservice.
> Merge Annotation microservice CI & CD config

- annotations/app.js
- frontend/src/components/ImageComponent.js
This PR achieves the solution to the bug reported on #523. By merging this we make sure that the annotation service and frontend services are working correctly together.
> Annotation microservice bugfix for production

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/components/AnnotatableText.js
- frontend/src/pages/ArtItemPage/ArtItemPage.js
- frontend/src/pages/DiscussionPage/DiscussionPostPage.js
- frontend/src/pages/EventPage/EventPage.js
- frontend/src/pages/HomePage/FeedCard.js
I have added text annotation to the frontend. Currently it doesn't send requests to the annotation service and it doesn't always work. Sometimes you need to refresh.
Only the descriptions of art items, events and discussion posts can be annotated.
This is in no way finished but we can maybe merge it for the presentation. We can discuss this tomorrow.
> Frontend text annotation

- backend/src/main/kotlin/com/group7/artshare/request/ArtItemRequest.kt
- backend/src/test/kotlin/com/group7/artshare/controller/ArtItemControllerTest.kt
Tests of four different scenarios for art item endpoints are implemented.
> Art Item Unit Tests

- backend/src/main/kotlin/com/group7/artshare/controller/ProfileController.kt
- backend/src/test/kotlin/com/group7/artshare/controller/ProfileControllerTest.kt
Added unit tests that covers five scenarios related to profile controllers.
> Profile Controller Unit Tests

- backend/src/main/kotlin/com/group7/artshare/service/CommentService.kt
- backend/src/main/kotlin/com/group7/artshare/service/DiscussionPostService.kt
The PR for the issue: https://github.com/bounswe/bounswe2022group7/issues/548
This is the initial information about comment(same logic applies for discussion post):
This is the result after sending the same vote to remove (it works like youtube like/dislike):
> add removing functionality in voting mechanism

- android/lib/models/post_model.dart
- android/lib/pages/home_page.dart
- android/lib/widgets/feed_container.dart
Home page does not request post images more than once. I explained the details in this [issue](https://github.com/bounswe/bounswe2022group7/issues/545)
> [Mobile] Home page image caching

- frontend/src/pages/ArtItemPage/ArtItemPage.js
- frontend/src/pages/ArtItemPage/AuctionDisplay.js
I have implemented the auction interface and integrated with the backend. I have described how it works in #583.
Closes #583.
> Frontend Art Item Auction Functionality

- frontend/src/common/UserCard.js
- frontend/src/components/CommentVote.js
- frontend/src/components/InteractiveIcon.js
I have added comment upvote/downvote functionality to the frontend. Details can be found in #588.
Closes #588.
> Comment Upvote Downvote Functionality

- frontend/src/pages/ProfilePage/Profile.js
User Level can be shown on profile page.
> [Frontend] User Level

- frontend/src/ResponsiveAppBar.js
- frontend/src/components/ArtItemPreview.js
- frontend/src/components/DiscussionPostPreview.js
- frontend/src/components/EventPreview.js
- frontend/src/pages/HomePage/FeedCard.js
- frontend/src/pages/HomePage/HomePage.js
- frontend/src/tests/FeedCard.test.js
This PR covers the changes described in #582. There are 3 component additions covering `ArtItem`, `Event` and `DiscussionPost` contents which can be also used in profile with its current version.
> [Frontend] Follow, bookmark, like, participate on Homepage

- android/lib/models/profile/account_model.dart
- android/lib/pages/profile_page.dart
I added the check if a profile page visited is already followed to change the "follow" button to "following"
[issue](https://github.com/bounswe/bounswe2022group7/issues/435)
> [Mobile] update the follow button for already followed users

- frontend/src/App.js
- frontend/src/ResponsiveAppBar.js
- frontend/src/pages/EventPage/CreateOnlineEventPage.js
- frontend/src/pages/EventPage/CreatePhysicalEventPage.js
- frontend/src/pages/EventPage/EventPage.js
- frontend/src/pages/EventPage/ImageCollection.js
I have added online exhibitions to the frontend and also added colaborate functionality to events.
Closes #595.
> [Frontend] Create and View Online Exhbition

- frontend/src/pages/HomePage/HomePage.js
This PR implements the changes described and shown in #613. The basic description is that a tab bar is added to change between recommended and all post views. 
Merging this PR closes #613.
> [Frontend] Added recommended and all post tabs to HomePage

- frontend/src/pages/ProfilePage/Profile.js
- frontend/src/tests/Profile.test.js
> [FE] Profile page test

- android/lib/models/post_model.dart
- android/lib/widgets/feed_container.dart
I implemented the bookmark feature for the feed posts in the mobile app, details are in this [issue](https://github.com/bounswe/bounswe2022group7/issues/587).
> [Mobile] Dev/android/feed page bookmarks

- android/lib/models/art_item/art_item_model.dart
- android/lib/network/art_item/post_art_item_auction_service.dart
I implemented the  the network connections of the auction feature for the mobile app, details are in [issue](https://github.com/bounswe/bounswe2022group7/issues/602)
> [Mobile] Dev/android/auction network

- android/lib/models/image_annotation_model.dart
- android/lib/network/annotation/get_annotation_service.dart
- android/lib/network/annotation/post_annotation_service.dart
- android/lib/pages/image_annotation_page.dart
This is a quick fix branch. With this branch,
1. The Image Annotation Page can be scrolled now.
2. A `creator` field is added to the Annotation objects.
> [Mobile] Image Annotation Fix

- frontend/src/App.js
- frontend/src/common/CopyrightReporter.js
- frontend/src/pages/ArtItemPage/ArtItemPage.js
- frontend/src/pages/HomePage/FeedCard.js
- frontend/src/pages/HomePage/HomePage.js
- frontend/src/tests/CopyrightReporter.test.js
This PR implements the changes described in #581. After a succesfull merge the relevant issue should also be closed.
> [Frontend] Add Copyright Report functionality for Art Items

- frontend/src/pages/ProfilePage/Profile.js
When the following button on the profile page is clicked, the list of followed users are displayed.
> [FE] Display following users on profile page

- frontend/src/App.js
- frontend/src/ResponsiveAppBar.js
- frontend/src/components/UserPreview.js
- frontend/src/pages/HomePage/HomePage.js
- frontend/src/pages/SearchPage/SearchPage.js
This PR contains the changes that add search functionality to frontend as described in #617. The changes include a working search bar and a search page listing the results of the search query.
Merging this PR closes #617.
> [Frontend] Adding search functionality

- frontend/src/pages/ProfilePage/Profile.js
- frontend/src/pages/SearchPage/SearchPage.js
This PR fixes the loading and user image not shown bugs in search page.
> [Frontend] Fix page load issue and user image issue in search

- README.md
This PR adds build & run instructions along with some information about our application.
> Add Build & Run instructions

- backend/src/test/kotlin/com/group7/artshare/controller/UserInteractionControllerTest.kt
Added unit tests to check all of the four different scenarious of follow function.
> UserInteractionEndpoint unit tests
